### ISSUE TITLE
does not start on Android 14

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [bahaaTuffaha/Project-ClosetArchive#21]
I want to start the app [Closet Archive on F-Droid]
(https://f-droid.org/packages/com.myclosetx/)
and then the app closes again.

My phone:
Samsung S21 5G
Android 14

**Comment by Coldtea3** [comment]
I haven't test it on android 14 😅 ... I will look into it Thank you.

**Comment by bahaaTuffaha** [comment]
I haven't test it on android 14 😅 ... I will look into it Thank you.

**Comment by bahaaTuffaha** [comment]
You can download the new release from [https://github.com/bahaaTuffaha/Project-ClosetArchive/releases](https://github.com/bahaaTuffaha/Project-ClosetArchive/releases)
while I push a request to f-droid...

**Comment by mondlicht-und-sterne** [comment]
@bahaaTuffaha 

Thank you for the fix.
I installed and i can start the app on Android 14.
