### ISSUE TITLE
Main collection window does not scroll

### ISSUE THREAD

**Issue by Daraf-it** [bahaaTuffaha/Project-ClosetArchive#28]
In the ClosetArchive main page the collection area does not scroll if the are more fields/collections than the visible space. Same issue in "select item" page of "record a log".

**Comment by Daraf-it** [comment]
Please, also put the possibility to change the name of the collections. 🙏🙏🙏🫶
Thank you.

**Comment by bahaaTuffaha** [comment]
Noted 👍
Thanks.

**Comment by bahaaTuffaha** [comment]
Fixed the issues in v1.0.4 update you can wait a couple of days to appear in f-droid or you can just download the apk from releases:
https://github.com/bahaaTuffaha/Project-ClosetArchive/releases/tag/v1.0.4

Feel free to post your feedback or any issues or even features to consider.

**Comment by Daraf-it** [comment]
> Feel free to post your feedback or any issues or even features to consider.

I will do 😊
Thank you.
