### ISSUE TITLE
What are all these permissions for?

### ISSUE THREAD

**Issue by Sera-Moon** [bahaaTuffaha/Project-ClosetArchive#30]
Hi,

this application seems pretty useful, but has so many permissions, which are in my opinion, not necessary. 

It is obvious, why storage permissions are necessary, and notifications also makes sense to get notified when to wash clothes.

But what about full network access, prevent phone from sleeping, view network connections, view WiFi connections, run at startup, control vibration (maybe for notifications?), scheduled precisely timed actions (reminder to wash clothes?) and Android Permissions: read app badge

Furthermore, does the app needs full storage access, or only have access to a specific folder? 
Because it might be dangerous if an app has full storage access and internet access without any reasons.

Hope someone can answer my questions.

**Comment by bahaaTuffaha** [comment]
hey,
Thanks for trying the app... to be honest I didn't touch any of these permissions (prevent phone from sleeping, view network connections, view WiFi connections, run at startup, control vibration) you can check the manifest:
https://github.com/bahaaTuffaha/Project-ClosetArchive/blob/main/android/app/src/main/AndroidManifest.xml
I absolutely care about privacy and these permissions are not needed if you could help removing them that would be awesome.
Thanks for pointing out .. I will look more about this matter maybe in the next update.

**Comment by bahaaTuffaha** [comment]
Oh the VIBRATE I think is needed for notifications

**Comment by bahaaTuffaha** [comment]
And I noticed that notifications in android 14 are not working currently for some reason..

**Comment by Daraf-it** [comment]
> Hi,
> 
> this application seems pretty useful, but has so many permissions, which are in my opinion, not necessary.
> 
> It is obvious, why storage permissions are necessary, and notifications also makes sense to get notified when to wash clothes.
> 
> But what about full network access, prevent phone from sleeping, view network connections, view WiFi connections, run at startup, control vibration (maybe for notifications?), scheduled precisely timed actions (reminder to wash clothes?) and Android Permissions: read app badge
> 
> Furthermore, does the app needs full storage access, or only have access to a specific folder? Because it might be dangerous if an app has full storage access and internet access without any reasons.
> 
> Hope someone can answer my questions.

Good questions! You've put a lot of worries in my mind...
For my own privacy, I have just protected the app with a firewall that prevents it from being connected to the outside world.

**Comment by Daraf-it** [comment]
Please, also remove the reminder notice of "log what you wear today". In my opinion it's just a useless and annoying thing...

**Comment by bahaaTuffaha** [comment]
It will show up every 12 hours ~ twice a day . I'm thinking to add a checkbox in the settings to disable this reminder 👍.

**Comment by bahaaTuffaha** [comment]
@Sera-Moon @Daraf-it 
Hey guys,
I'm still investigating how can I remove these permissions:
1- I tried to add for example: 
`<uses-permission
    android:name="android.permission.WAKE_LOCK"
    tools:node="remove" />`
At AndroidManifest.xml but it didn't work.

2- Also from expo modules:
`"android": {
  // ...
  "blockedPermissions": [
    "android.permission.WAKE_LOCK",
     "android.permission.INTERNET"
  ]
}
`
At app.json or even package.json
Non of these worked.
What I suspect is that one of the libraries like react-native-push-notification or expo modules are using these permissions and if I removed for example RECEIVE_BOOT_COMPLETED permission it will crash 😓. The crazy thing that why it needs WiFi connections if the INTERNET permission is removed?😭.

I'm open for any suggestions or contributions to fix this issue. And Thank you😊.

**Comment by bahaaTuffaha** [comment]
@Sera-Moon @Daraf-it 
I found the issue I forgot to add xmlns:tools="http://schemas.android.com/tools" in AndroidManifest.xml:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>
    <uses-permission android:name="android.permission.USE_EXACT_ALARM" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
    <uses-permission tools:node="remove" android:name="android.permission.INTERNET" />
    <uses-permission tools:node="remove" android:name="android.permission.WAKE_LOCK" />
    <uses-permission tools:node="remove" android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission tools:node="remove" android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission tools:node="remove" android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />`
    
    an Update coming in hot!!🔥🔥🚀

**Comment by bahaaTuffaha** [comment]
https://github.com/bahaaTuffaha/Project-ClosetArchive/releases/tag/v1.0.5
Have a great day gentlemen 🎩.
