### ISSUE TITLE
Type-specific laundry reminder

### ISSUE THREAD

**Issue by eg-mart** [bahaaTuffaha/Project-ClosetArchive#31]
Current laundry reminder allows to set the same maximum number of wears for every item, but it would be far more useful if it allowed to set different numbers for different types of items, for example: t-shirts - 2 wears, underwear - 1 wear, etc. Even pre-set different numbers of wears would be a huge improvement, in my opinion.

**Comment by bahaaTuffaha** [comment]
Thank you for using the app..
Noted 👍 ... I'm thinking of adding an override input field for each item that gives you an option to override the number of wears.

**Comment by eg-mart** [comment]
Cool! Will be waiting for this feature in the next updates

**Comment by bahaaTuffaha** [comment]
Done.
https://github.com/bahaaTuffaha/Project-ClosetArchive/releases/tag/v1.0.6
