### ISSUE TITLE
Italian language done!

### ISSUE THREAD

**Issue by Daraf-it** [bahaaTuffaha/Project-ClosetArchive#33]
I took the liberty of translating into Italian. I don't know how to use github so I'm attaching it here. In data.ts the localization of "const FitList" is missing, so it is not translatable.
[localization.ts.txt](https://github.com/bahaaTuffaha/Project-ClosetArchive/files/15131918/localization.ts.txt)
[data.ts.txt](https://github.com/bahaaTuffaha/Project-ClosetArchive/files/15131403/data.ts.txt)
Do a quickly check for any code errors.
Tell me if there are other ClosetArchive files to translate 😊

**Comment by bahaaTuffaha** [comment]
Thank you so much ❤️
I will add this in the next update...
I didn't know how to translate the FitList properly so I left it as it is.
It would be cool if you made a pull request to keep your name attached to these changes and I will review it if there is something wrong.

**Comment by Daraf-it** [comment]
I checked localization.ts file again:
In lines 68, 142,  162, 211, 615 end line comma is missing (maybe it is not mandatory).

**Comment by bahaaTuffaha** [comment]
Yes the last index can be without comma 👍.
I will check crowdin website Thanks 🫡.
Actually I did use chatGPT for the Spanish 😅.

**Comment by bahaaTuffaha** [comment]
https://github.com/bahaaTuffaha/Project-ClosetArchive/releases/tag/v1.0.6
I added the Italian + added new lines. Let me know if there is anything needs modifying.

**Comment by Daraf-it** [comment]
Where are new lines? Localizations.ts file only?

**Comment by Daraf-it** [comment]
Done.
[localization.ts.05052022.txt](https://github.com/bahaaTuffaha/Project-ClosetArchive/files/15211556/localization.ts.05052022.txt)

**Comment by bahaaTuffaha** [comment]
Thank You!

**Comment by Daraf-it** [comment]
Today I installed the latest version. I noticed that you have modified some of my translations (e.g.: line 711 of the localization.ts file and I don't understand the reasons). In any case, with the experience of use, I think that some parts need to be modified. If you wish, I will provide.
The construction of the sentence in Italian is completely different and more complex than in English. For example, the English sentence "Shoes category has:" must be translated into Italian "La categoria scarpe ha:" where the words are reversed in place, so the meaning will always be "a little out of tune".

**Comment by bahaaTuffaha** [comment]
I pushed these updates before your latest translation because usually it takes week or so to be processed and published to f-droid. Definitely the next update will contain these changes... sorry about that😅.

**Comment by Daraf-it** [comment]
Well... no problem.😉. But my last translation need some modify too. It will be a "fine tune" steps.
I will attach new file quiclky.

**Comment by bahaaTuffaha** [comment]
Take your time 👍

**Comment by Daraf-it** [comment]
[localization.120522.ts.txt](https://github.com/bahaaTuffaha/Project-ClosetArchive/files/15285312/localization.120522.ts.txt)

**Comment by bahaaTuffaha** [comment]
I will add these two sentences, anything to change here?
`  Edit_Category: [
    "Edit Category",
    "تعديل الفئة",
    "Editar categoría",
    "Modifica categoria",
  ],
  Add_Type: ["Add Type", "إضافة نوع", "Añadir tipo", "Aggiungi tipo"],`

**Comment by bahaaTuffaha** [comment]
Also is there a shorter form for "Closet Info" in Italian?
![image](https://github.com/bahaaTuffaha/Project-ClosetArchive/assets/101111168/2b6de680-edf1-449e-901e-e5e3d9877993)

**Comment by Daraf-it** [comment]
> I will add these two sentences, anything to change here? ` Edit_Category: [ "Edit Category", "تعديل الفئة", "Editar categoría", "Modifica categoria", ], Add_Type: ["Add Type", "إضافة نوع", "Añadir tipo", "Aggiungi tipo"],`

Good.


> Also is there a shorter form for "Closet Info" in Italian? ![image](https://private-user-images.githubusercontent.com/101111168/333875031-2b6de680-edf1-449e-901e-e5e3d9877993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDIwMjUsIm5iZiI6MTcxNjc0MTcyNSwicGF0aCI6Ii8xMDExMTExNjgvMzMzODc1MDMxLTJiNmRlNjgwLWVkZjEtNDQ5ZS05MDFlLWU1ZTNkOTg3Nzk5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxNjQyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWYyMzljNzQ3MDUwYWE4MWM2MmIxYTA2ODY3MWU3NjJjZWE3OTg3YTllOTk1MDIwNmY0ZmRjYWZkOTdkOWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cBSEpZ1J-PHBUf-tDBghTEtU4NLpUtaMCgUc-yUPUWc)
You could edit "Info su Armadio"

**Comment by bahaaTuffaha** [comment]
Thank You🙏
