### ISSUE TITLE
Add Types to preexisting Categories

### ISSUE THREAD

**Issue by tdadvocate** [bahaaTuffaha/Project-ClosetArchive#34]
I'd love to be able to edit the clothing types for the preexisting categories within the app. Especially since custom categories can't have clothing types or main icons. This could really help to add some better spring cleaning for people looking to get rid of or purchase new outfits. That way, they know what they might be missing or need matches to. Otherwise this app really does seem very useful. Thank you very much for creating this app! I really love the fun design language it has too. Very unique!

**Comment by bahaaTuffaha** [comment]
Thank you so much for your kind words!❤️ I'm thrilled to hear that you find the app useful and that you appreciate the design language. I will look into a way to make this editing types possible and maybe adding a set of icons for the user to select from... it could be after the next update that I'm working on.

**Comment by bahaaTuffaha** [comment]
https://github.com/bahaaTuffaha/Project-ClosetArchive/releases/tag/v1.0.8
If you have any feedback, issues or suggestions please let me know 🙏...

**Comment by tdadvocate** [comment]
The new update looks amazing! I can't wait to try it out fully with my wardrobe. Thank you for all of your hard work on this app! I will definitely let you know if I run across any bugs, but so far, it's all been working great!
